### ISSUE TITLE
Requires sketch.h

### ISSUE THREAD

**Issue by Kavicy** [RabbitBio/RabbitTClust#13]
`In file included from /home/RabbitTClust/RabbitTClust/RabbitSketch/src/SketchInfo.cpp:1:
/home/RabbitTClust/RabbitTClust/RabbitSketch/src/SketchInfo.h:4:10: fatal error: Sketch.h: No such file or directory
    4 | #include "Sketch.h"
      |          ^~~~~~~~~~
In file included from /home/RabbitTClust/RabbitTClust/RabbitSketch/src/greedy.h:5,
                 from /home/RabbitTClust/RabbitTClust/RabbitSketch/src/greedy.cpp:2:
/home/RabbitTClust/RabbitTClust/RabbitSketch/src/SketchInfo.h:4:10: fatal error: Sketch.h: No such file or directory
    4 | #include "Sketch.h"
      |          ^~~~~~~~~~
compilation terminated.
compilation terminated.
In file included from /home/RabbitTClust/RabbitTClust/RabbitSketch/src/Sketch_IO.h:3,
                 from /home/RabbitTClust/RabbitTClust/RabbitSketch/src/Sketch_IO.cpp:1:
/home/RabbitTClust/RabbitTClust/RabbitSketch/src/SketchInfo.h:4:10: fatal error: Sketch.h: No such file or directory
    4 | #include "Sketch.h"
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/clust-greedy.dir/build.make:132: CMakeFiles/clust-greedy.dir/src/greedy.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/clust-greedy.dir/build.make:118: CMakeFiles/clust-greedy.dir/src/Sketch_IO.cpp.o] Error 1
make[2]: *** [CMakeFiles/clust-greedy.dir/build.make:104: CMakeFiles/clust-greedy.dir/src/SketchInfo.cpp.o] Error 1
In file included from /home/RabbitTClust/RabbitTClust/RabbitSketch/src/main.cpp:20:
/home/RabbitTClust/RabbitTClust/RabbitSketch/src/SketchInfo.h:4:10: fatal error: Sketch.h: No such file or directory
    4 | #include "Sketch.h"
      |          ^~~~~~~~~~
compilation terminated.`
Hello, when I compile sketchinfo, it prompts that sketch.h is missing, but I don't see this header file in the source code. Can you provide a solution?

**Comment by ZekunYin** [comment]
Hi, 
Did you clone this project recursively? Using a command like this `git clone --recursive https://github.com/RabbitBio/RabbitTClust.git`. 
Since our RabbitTClust relies on RabbitSketch library.
If there is still a compilation problem, please feel free to conatact me!

Best,
Zekun

**Comment by Kavicy** [comment]
Thanks, it seems the problem has been solved after I re-tried the installation

**Comment by Kavicy** [comment]
> Hi, Did you clone this project recursively? Using a command like this `git clone --recursive https://github.com/RabbitBio/RabbitTClust.git`. Since our RabbitTClust relies on RabbitSketch library. If there is still a compilation problem, please feel free to conatact me!
> 
> Best, Zekun

Thanks, it seems the problem has been solved after I re-tried the installation
