### ISSUE TITLE
Incorrect Error Message

### ISSUE THREAD

**Issue by amyliufda** [RabbitBio/RabbitTClust#6]
The latest two versions, 2.2.0 and 2.2.1 work well so far.  However, we encountered a misleading error with the '-i' option.  If the input file is not found, it prints out 'Floating point exception' error which doesn't help user find the real issue quickly.  "Input file not found" would be a better one.

**Comment by XiaomingXu1995** [comment]
Hi amyliufda,
Thank you for this issue!

I have updated the Error Message for checking the input file.

Best,
Xiaoming
