### ISSUE TITLE
Add  RabbitTClust to Bioconda

### ISSUE THREAD

**Issue by apcamargo** [RabbitBio/RabbitTClust#8]
Hi @XiaomingXu1995 

First, I'd like to congratulate you for RabbitTClust. I spent weeks trying to find a clustering algorithm that worked in the scale I needed and RabbitTClust solved all of my problems.

Do you think you can publish it in Bioconda? Right now I need to compile it and not everyone (or everyserver) has Cmake available. It would be great to have it in Bioconda to make installation easy.

**Comment by XiaomingXu1995** [comment]
Hi, 

Thanks for your issue. That's a good idea. 

I'm on a business trip, and I will publish it in Bioconda as long as I finish the trip!

Best,
Xiaoming

**Comment by apcamargo** [comment]
Thank you!

**Comment by apcamargo** [comment]
Hi @XiaomingXu1995,

I started to put together a recipe for Bioconda. However, Bioconda downloads the source directly from the "Assets" section of GitHub releases page and it seems that the `.tar.gz` files you have there don't include the submodules.

Can you include the file that include the submodules in the "Assets"? Do do that, you can just edit the release and drop the file into the "_Attach binaries by dropping them here or selecting them._" area.

**Comment by XiaomingXu1995** [comment]
Hi, 
Please accept my apologies for the delay in getting back to you about it.

I have updated all source codes including the submodules in to the realease.

Best,
Xiaoming

**Comment by sorenwacker** [comment]
Hi, we were trying to compile the code, but run into multiple issues. Having an easier way to install the software would be great.

**Comment by jianshu93** [comment]
Hello All, 

I have the same problems with compiling (alway some errors). For the submodule problems, do not link to another github page but just copy them to this repo will solve the problem. I look forward to it just becuase this is the only tool to greedy clustering the genomes to find some repentatives. It would be nice to also provide a Linux binary before adding to bioconda (It takes some time).

Thanks,

Jianshu

**Comment by XiaomingXu1995** [comment]
Hi, everyone, RabbitTClust is availabe at https://anaconda.org/bioconda/rabbittclust.

**Comment by jianshu93** [comment]
Thank you！

Best，

Jianshu
